steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-west2-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/quickstart-image:$TAG_NAME'
      - '--target'
      - 'app_all_inclusive'
      - '.'
images:
  - 'europe-west6-docker.pkg.dev/maidmaid/ch-holidays/ch-holidays:$TAG_NAME'
