steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull $_REGISTRY_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest || exit 0'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--target'
      - 'app_all_inclusive'
      - '-t'
      - '$_REGISTRY_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$TAG_NAME'
      - '-t'
      - '$_REGISTRY_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_REGISTRY_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$TAG_NAME'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
images:
  - '$_REGISTRY_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$TAG_NAME'
  - '$_REGISTRY_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest'
timeout: 1800s
options:
  machineType: E2_HIGHCPU_8
  substitutionOption: ALLOW_LOOSE
substitutions:
  _DEPLOY_REGION: europe-west6
  _REGISTRY_HOSTNAME: europe-west6-docker.pkg.dev
  _PLATFORM: managed
  _LABELS: gcb-trigger-id=0944bd10-c3a2-4738-a610-d0cd3b2e6f71
  _TRIGGER_ID: 0944bd10-c3a2-4738-a610-d0cd3b2e6f71
  _SERVICE_NAME: ch-holidays
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - ch-holidays
