steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c', 'docker pull europe-west6-docker.pkg.dev/$PROJECT_ID/ch-holidays:latest || exit 0' ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--target app_all_inclusive'
      - '-t europe-west6-docker.pkg.dev/$PROJECT_ID/ch-holidays:$TAG_NAME'
      - '-t europe-west6-docker.pkg.dev/$PROJECT_ID/ch-holidays:latest'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'
images:
  - 'europe-west6-docker.pkg.dev/$PROJECT_ID/ch-holidays:$TAG_NAME'
  - 'europe-west6-docker.pkg.dev/$PROJECT_ID/ch-holidays:latest'
timeout: 1800s
